// Code generated by MockGen. DO NOT EDIT.
// Source: app/infrastructure/setup_dependencies/dependencies.go

// Package mock_setup_dependencies is a generated GoMock package.
package mock_setup_dependencies

import (
	os "os"
	reflect "reflect"

	config "cnores-skeleton-golang-app/app/shared/utils/config"
	log "cnores-skeleton-golang-app/app/shared/utils/log"
	gomock "github.com/golang/mock/gomock"
)

// MockInfrastructureInterface is a mock of InfrastructureInterface interface.
type MockInfrastructureInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInfrastructureInterfaceMockRecorder
}

// MockInfrastructureInterfaceMockRecorder is the mock recorder for MockInfrastructureInterface.
type MockInfrastructureInterfaceMockRecorder struct {
	mock *MockInfrastructureInterface
}

// NewMockInfrastructureInterface creates a new mock instance.
func NewMockInfrastructureInterface(ctrl *gomock.Controller) *MockInfrastructureInterface {
	mock := &MockInfrastructureInterface{ctrl: ctrl}
	mock.recorder = &MockInfrastructureInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfrastructureInterface) EXPECT() *MockInfrastructureInterfaceMockRecorder {
	return m.recorder
}

// GraceFullShutdown mocks base method.
func (m *MockInfrastructureInterface) GraceFullShutdown(sig os.Signal, log *log.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GraceFullShutdown", sig, log)
}

// GraceFullShutdown indicates an expected call of GraceFullShutdown.
func (mr *MockInfrastructureInterfaceMockRecorder) GraceFullShutdown(sig, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GraceFullShutdown", reflect.TypeOf((*MockInfrastructureInterface)(nil).GraceFullShutdown), sig, log)
}

// SetupDependencies mocks base method.
func (m *MockInfrastructureInterface) SetupDependencies(config config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupDependencies", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupDependencies indicates an expected call of SetupDependencies.
func (mr *MockInfrastructureInterfaceMockRecorder) SetupDependencies(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDependencies", reflect.TypeOf((*MockInfrastructureInterface)(nil).SetupDependencies), config)
}
